apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
        - cluster: devel
          url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'cert-manager-{{.cluster}}'
    spec:
      project: default
      source:
        chart: cert-manager
        repoURL: https://charts.jetstack.io
        targetRevision: 1.18.2
        helm:
          releaseName: cert-manager
          values: |
            serviceAccount:
              create: true
              annotations:
                eks.amazonaws.com/role-arn: arn:aws:iam::273729230602:role/eks1-devel-cert-manager
            extraObjects: |
              apiVersion: cert-manager.io/v1
              kind: Issuer
              metadata:
                name: letsencrypt-staging
              spec:
                acme:
                  server: https://acme-staging-v02.api.letsencrypt.org/directory
                  email: rcavicchioni@gmail.com
                  profile: tlsserver
                  privateKeySecretRef:
                    name: letsencrypt-staging
                  solvers:
                    - http01:
                        ingress:
                          ingressClassName: nginx
      destination:
        server: '{{.url}}'
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

