apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-autoscaler
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: development
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'cluster-autoscaler-{{.cluster}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/ryanc/argocd.git
        targetRevision: HEAD
        path: cluster-autoscaler/envs/{{.cluster}}
      destination:
        server: '{{.url}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
