apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
        - cluster: devel
          url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'ingress-nginx-{{.cluster}}'
    spec:
      project: default
      source:
        chart: ingress-nginx
        repoURL: https://kubernetes.github.io/ingress-nginx
        targetRevision: 4.13.0
        helm:
          releaseName: ingress-nginx
          values: | 
            service:
              annotations:
                service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: deregistration_delay.timeout_seconds=270
                service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
                service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /healthz
                service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "10254"
                service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: http
                service.beta.kubernetes.io/aws-load-balancer-healthcheck-success-codes: 200-299
                service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
                service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
                service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
                service.beta.kubernetes.io/aws-load-balancer-type: nlb
                service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules: "true"
                service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
                service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-something1 sg-something2"
                service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: "somebucket"
                service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: "ingress-nginx"
                service.beta.kubernetes.io/aws-load-balancer-access-log-emit-interval: "5"
      destination:
        server: '{{.url}}'
        namespace: ingress-nginx
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

