---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-autoscaler
resources:
  - ../../base
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cluster-autoscaler
        namespace: kube-system
      spec:
        template:
          spec:
            containers:
              - name: cluster-autoscaler
                command:
                  - ./cluster-autoscaler
                  - --v=4
                  - --stderrthreshold=info
                  - --cloud-provider=aws
                  - --skip-nodes-with-local-storage=false
                  - --expander=least-waste
                  - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/eks1-devel
